import {supabase,authConfig} from '@/lib/supabase';
import {checkOrigin,failure} from '@/lib/server';
export async function POST(req:Request){try{checkOrigin(req);const b=await req.json() as any;const client=await supabase();const c=authConfig();const redirect=(c.site||new URL(req.url).origin)+'/auth/finish';let result:any;
if(b.action==='oauth'){if(!['google','apple'].includes(b.provider)||(b.provider==='google'&&!c.google)||(b.provider==='apple'&&!c.apple))throw new Error('This sign-in provider is not available yet.');result=await client.auth.signInWithOAuth({provider:b.provider,options:{redirectTo:redirect,skipBrowserRedirect:true}});}
else if(b.action==='logout')result=await client.auth.signOut();
else if(b.action==='refresh')result=await client.auth.getUser();
else if(b.action==='updatePassword'){if(typeof b.password!=='string'||b.password.length<12||b.password.length>128)throw new Error('Use a password with 12–128 characters.');result=await client.auth.updateUser({password:b.password});}
else{if(typeof b.email!=='string'||b.email.length>254||!b.email.includes('@'))throw new Error('Enter a valid email address.');if(b.action==='reset')result=await client.auth.resetPasswordForEmail(b.email,{redirectTo:redirect+'?next=/reset-password'});else{if(typeof b.password!=='string'||!b.password.length||b.password.length>128||(b.action==='signup'&&b.password.length<12))throw new Error('Check your password. New passwords need 12–128 characters.');if(b.action==='signup')result=await client.auth.signUp({email:b.email,password:b.password,options:{emailRedirectTo:redirect}});else if(b.action==='login')result=await client.auth.signInWithPassword({email:b.email,password:b.password});else throw new Error('Unknown action.');}}
if(result.error&&(result.error.name==='AuthRetryableFetchError'||!result.error.status))throw new Error('Could not reach the sign-in service. Please try again in a moment.');if(result.error)throw new Error(b.action==='login'?'Sign-in failed. Check your email, password, and email confirmation.':result.error.message);return Response.json({ok:true,url:result.data?.url,confirm:b.action==='signup'&&!result.data?.session},{headers:{'Cache-Control':'no-store'}});
}catch(e){return failure(e)}}
