'use client';
import React,{createContext,useContext,useState,useEffect} from 'react';
import {Globe} from 'lucide-react';
import dictionary from './translations.json';
export type Language='en'|'nl'|'fr'|'es';
const labels={en:'English',nl:'Nederlands',fr:'Français',es:'Español'};
const Context=createContext({lang:'en' as Language,setLang:(v:Language)=>{void v}});
export function useLanguage(){return useContext(Context)}
export function translate(value:string,lang:Language):string{if(lang==='en')return value;const trimmed=value.trim();const dict=dictionary as Record<string,string[]>;const hit=dict[trimmed];if(hit)return value.replace(trimmed,hit[{nl:0,fr:1,es:2}[lang]]);for(const prefix of ['Open ','Unsave ','Save ','Remove ','What’s for ','Meal added to ']){if(trimmed.startsWith(prefix)){const rest=trimmed.slice(prefix.length);const question=rest.endsWith('?');const content=translate(question?rest.slice(0,-1):rest,lang);return translate(prefix.trim(),lang)+' '+(['What’s for ','Meal added to '].includes(prefix)?content.toLocaleLowerCase(lang):content)+(question?'?':'')}}if(trimmed.endsWith(' ingredients ready for a little magic'))return trimmed.replace('ingredients ready for a little magic',translate('ingredients ready for a little magic',lang));return value}
export function localize(node:React.ReactNode,lang:Language):React.ReactNode{if(typeof node==='string')return translate(node,lang);if(Array.isArray(node))return node.map(n=>localize(n,lang));if(!React.isValidElement(node))return node;const p=node.props as any;if(p['data-no-translate'])return node;const next:any={};for(const k of ['placeholder','aria-label','title','alt'])if(typeof p[k]==='string')next[k]=translate(p[k],lang);if(Array.isArray(p.children))return React.cloneElement(node,next,...(localize(p.children,lang) as React.ReactNode[]));if(p.children!==undefined)next.children=localize(p.children,lang);return React.cloneElement(node,next)}
export function LanguageProvider({children}:{children:React.ReactNode}){const [lang,setLanguage]=useState<Language>('en');useEffect(()=>{try{const stored=localStorage.getItem('simmerfolk-language');if(stored&&stored in labels)setLanguage(stored as Language)}catch{}},[]);useEffect(()=>{document.documentElement.lang=lang},[lang]);function setLang(v:Language){setLanguage(v);try{localStorage.setItem('simmerfolk-language',v)}catch{}}return <Context.Provider value={{lang,setLang}}>{children}</Context.Provider>}
export function LanguagePicker({expanded=false}:{expanded?:boolean}){const {lang,setLang}=useLanguage();if(expanded)return <div className="language-options">{Object.entries(labels).map(([code,label])=><button key={code} lang={code} className={lang===code?'active':''} onClick={()=>setLang(code as Language)} aria-pressed={lang===code}>{label}</button>)}</div>;return <label className="language-control"><Globe size={17}/><select aria-label={translate('Site language',lang)} value={lang} onChange={e=>setLang(e.target.value as Language)}>{Object.entries(labels).map(([code,label])=><option value={code} key={code}>{label}</option>)}</select></label>}
